export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = "customer" | "dealer" | "admin";
export type OrderStatus = "pending" | "processing" | "shipped" | "delivered" | "cancelled";
export type SubscriptionStatus = "active" | "paused" | "cancelled";
export type BoxSize = "starter" | "voyager" | "bunker";
export type DealerTier = "bronze" | "silver" | "gold" | "platinum";
export type InteractionChannel = "web" | "voice" | "sms" | "email" | "ai_bot";
export type MachineStatus = "online" | "offline" | "maintenance" | "low_stock";
export type BundleType = "fixed" | "custom";
export type ReviewStatus = "pending" | "approved" | "rejected";
export type RelationshipType = "pairs_with" | "also_bought" | "upgrade";
export type DiscountType = "percentage" | "fixed_amount" | "free_shipping" | "bogo" | "bundle" | "volume";
export type TriggerType = "automatic" | "coupon_code" | "referral";
export type CreditType = "earned_purchase" | "earned_referral" | "earned_review" | "redeemed" | "expired" | "adjustment";
export type ReferralStatus = "pending" | "signed_up" | "converted" | "rewarded";
export type GiftType = "box" | "subscription" | "gift_card";
export type ContractStatus = "draft" | "active" | "expired" | "terminated";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          role: UserRole;
          phone: string | null;
          address: Json | null;
          credits: number;
          organization_id: string | null;
          churn_risk_score: number | null;
          taste_preferences: Json | null;
          dietary_restrictions: string[] | null;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: UserRole;
          phone?: string | null;
          address?: Json | null;
          credits?: number;
          organization_id?: string | null;
          churn_risk_score?: number | null;
          taste_preferences?: Json | null;
          dietary_restrictions?: string[] | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: UserRole;
          phone?: string | null;
          address?: Json | null;
          credits?: number;
          organization_id?: string | null;
          churn_risk_score?: number | null;
          taste_preferences?: Json | null;
          dietary_restrictions?: string[] | null;
          metadata?: Json | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          logo_url: string | null;
          custom_domain: string | null;
          dealer_tier: DealerTier;
          stripe_connect_id: string | null;
          commission_rate: number;
          contact_email: string;
          contact_phone: string | null;
          address: Json | null;
          metadata: Json | null;
          is_active: boolean;
          payment_terms: string;
          credit_limit: number;
          current_balance: number;
          tax_exempt: boolean;
          tax_id: string | null;
          min_order_amount: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          logo_url?: string | null;
          custom_domain?: string | null;
          dealer_tier?: DealerTier;
          stripe_connect_id?: string | null;
          commission_rate?: number;
          contact_email: string;
          contact_phone?: string | null;
          address?: Json | null;
          metadata?: Json | null;
          is_active?: boolean;
          payment_terms?: string;
          credit_limit?: number;
          current_balance?: number;
          tax_exempt?: boolean;
          tax_id?: string | null;
          min_order_amount?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          logo_url?: string | null;
          custom_domain?: string | null;
          dealer_tier?: DealerTier;
          stripe_connect_id?: string | null;
          commission_rate?: number;
          contact_email?: string;
          contact_phone?: string | null;
          address?: Json | null;
          metadata?: Json | null;
          is_active?: boolean;
          payment_terms?: string;
          credit_limit?: number;
          current_balance?: number;
          tax_exempt?: boolean;
          tax_id?: string | null;
          min_order_amount?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      aura_products: {
        Row: {
          id: string;
          sku: string;
          name: string;
          description: string | null;
          short_description: string | null;
          price: number;
          compare_at_price: number | null;
          cost_price: number | null;
          image_url: string | null;
          images: string[];
          stock_level: number;
          is_bunker_safe: boolean;
          shelf_life_months: number | null;
          weight_oz: number | null;
          nutritional_info: Json | null;
          ingredients: string | null;
          allergens: string[] | null;
          category: string;
          tags: string[];
          is_active: boolean;
          sort_order: number;
          allergens_enum: string[];
          dietary_labels: string[];
          preparation_instructions: string | null;
          storage_instructions: string | null;
          is_seasonal: boolean;
          is_limited_edition: boolean;
          available_from: string | null;
          available_until: string | null;
          country_of_origin: string | null;
          brand: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sku: string;
          name: string;
          description?: string | null;
          short_description?: string | null;
          price: number;
          compare_at_price?: number | null;
          cost_price?: number | null;
          image_url?: string | null;
          images?: string[];
          stock_level?: number;
          is_bunker_safe?: boolean;
          shelf_life_months?: number | null;
          weight_oz?: number | null;
          nutritional_info?: Json | null;
          ingredients?: string | null;
          allergens?: string[] | null;
          category: string;
          tags?: string[];
          is_active?: boolean;
          sort_order?: number;
          allergens_enum?: string[];
          dietary_labels?: string[];
          preparation_instructions?: string | null;
          storage_instructions?: string | null;
          is_seasonal?: boolean;
          is_limited_edition?: boolean;
          available_from?: string | null;
          available_until?: string | null;
          country_of_origin?: string | null;
          brand?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          sku?: string;
          name?: string;
          description?: string | null;
          short_description?: string | null;
          price?: number;
          compare_at_price?: number | null;
          cost_price?: number | null;
          image_url?: string | null;
          images?: string[];
          stock_level?: number;
          is_bunker_safe?: boolean;
          shelf_life_months?: number | null;
          weight_oz?: number | null;
          nutritional_info?: Json | null;
          ingredients?: string | null;
          allergens?: string[] | null;
          category?: string;
          tags?: string[];
          is_active?: boolean;
          sort_order?: number;
          allergens_enum?: string[];
          dietary_labels?: string[];
          preparation_instructions?: string | null;
          storage_instructions?: string | null;
          is_seasonal?: boolean;
          is_limited_edition?: boolean;
          available_from?: string | null;
          available_until?: string | null;
          country_of_origin?: string | null;
          brand?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          image_url: string | null;
          parent_id: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          image_url?: string | null;
          parent_id?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          description?: string | null;
          image_url?: string | null;
          parent_id?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      organization_price_rules: {
        Row: {
          id: string;
          organization_id: string;
          product_id: string | null;
          category: string | null;
          discount_percentage: number | null;
          fixed_price: number | null;
          min_quantity: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          product_id?: string | null;
          category?: string | null;
          discount_percentage?: number | null;
          fixed_price?: number | null;
          min_quantity?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          organization_id?: string;
          product_id?: string | null;
          category?: string | null;
          discount_percentage?: number | null;
          fixed_price?: number | null;
          min_quantity?: number | null;
          is_active?: boolean;
        };
        Relationships: [];
      };
      aura_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          stripe_subscription_id: string | null;
          box_size: BoxSize;
          box_config: string[];
          status: SubscriptionStatus;
          price: number;
          next_delivery_date: string | null;
          delivery_frequency_days: number;
          shipping_address: Json;
          auto_fill_enabled: boolean;
          pause_until: string | null;
          cancelled_at: string | null;
          cancellation_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          stripe_subscription_id?: string | null;
          box_size: BoxSize;
          box_config?: string[];
          status?: SubscriptionStatus;
          price: number;
          next_delivery_date?: string | null;
          delivery_frequency_days?: number;
          shipping_address: Json;
          auto_fill_enabled?: boolean;
          pause_until?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          stripe_subscription_id?: string | null;
          box_size?: BoxSize;
          box_config?: string[];
          status?: SubscriptionStatus;
          price?: number;
          next_delivery_date?: string | null;
          delivery_frequency_days?: number;
          shipping_address?: Json;
          auto_fill_enabled?: boolean;
          pause_until?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      subscription_selections: {
        Row: {
          id: string;
          subscription_id: string;
          delivery_date: string;
          product_ids: string[];
          is_confirmed: boolean;
          confirmed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          subscription_id: string;
          delivery_date: string;
          product_ids: string[];
          is_confirmed?: boolean;
          confirmed_at?: string | null;
          created_at?: string;
        };
        Update: {
          subscription_id?: string;
          delivery_date?: string;
          product_ids?: string[];
          is_confirmed?: boolean;
          confirmed_at?: string | null;
        };
        Relationships: [];
      };
      aura_orders: {
        Row: {
          id: string;
          order_number: string;
          user_id: string;
          subscription_id: string | null;
          organization_id: string | null;
          dealer_attribution_id: string | null;
          stripe_payment_intent_id: string | null;
          stripe_invoice_id: string | null;
          status: OrderStatus;
          subtotal: number;
          discount: number;
          shipping: number;
          tax: number;
          total: number;
          currency: string;
          items: Json;
          shipping_address: Json;
          billing_address: Json | null;
          tracking_number: string | null;
          tracking_url: string | null;
          shipped_at: string | null;
          delivered_at: string | null;
          notes: string | null;
          internal_notes: string | null;
          purchase_type: string;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number: string;
          user_id: string;
          subscription_id?: string | null;
          organization_id?: string | null;
          dealer_attribution_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_invoice_id?: string | null;
          status?: OrderStatus;
          subtotal: number;
          discount?: number;
          shipping?: number;
          tax?: number;
          total: number;
          currency?: string;
          items: Json;
          shipping_address: Json;
          billing_address?: Json | null;
          tracking_number?: string | null;
          tracking_url?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          notes?: string | null;
          internal_notes?: string | null;
          purchase_type?: string;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          order_number?: string;
          subscription_id?: string | null;
          organization_id?: string | null;
          dealer_attribution_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_invoice_id?: string | null;
          status?: OrderStatus;
          subtotal?: number;
          discount?: number;
          shipping?: number;
          tax?: number;
          total?: number;
          currency?: string;
          items?: Json;
          shipping_address?: Json;
          billing_address?: Json | null;
          tracking_number?: string | null;
          tracking_url?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          notes?: string | null;
          internal_notes?: string | null;
          purchase_type?: string;
          metadata?: Json | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string;
          sku: string;
          name: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id: string;
          sku: string;
          name: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          created_at?: string;
        };
        Update: {
          order_id?: string;
          product_id?: string;
          sku?: string;
          name?: string;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
        };
        Relationships: [];
      };
      dealers: {
        Row: {
          id: string;
          profile_id: string;
          organization_id: string;
          qr_code_url: string | null;
          referral_code: string;
          commission_earned: number;
          commission_paid: number;
          commission_pending: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          organization_id: string;
          qr_code_url?: string | null;
          referral_code: string;
          commission_earned?: number;
          commission_paid?: number;
          commission_pending?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          qr_code_url?: string | null;
          referral_code?: string;
          commission_earned?: number;
          commission_paid?: number;
          commission_pending?: number;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      commission_transactions: {
        Row: {
          id: string;
          dealer_id: string;
          order_id: string | null;
          amount: number;
          type: string;
          status: string;
          stripe_payout_id: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          dealer_id: string;
          order_id?: string | null;
          amount: number;
          type: string;
          status?: string;
          stripe_payout_id?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          dealer_id?: string;
          order_id?: string | null;
          amount?: number;
          type?: string;
          status?: string;
          stripe_payout_id?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      inventory: {
        Row: {
          id: string;
          product_id: string;
          warehouse_location: string;
          quantity: number;
          reserved_quantity: number;
          safety_stock: number;
          reorder_point: number;
          reorder_quantity: number;
          last_restock_date: string | null;
          next_restock_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          warehouse_location?: string;
          quantity?: number;
          reserved_quantity?: number;
          safety_stock?: number;
          reorder_point?: number;
          reorder_quantity?: number;
          last_restock_date?: string | null;
          next_restock_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          warehouse_location?: string;
          quantity?: number;
          reserved_quantity?: number;
          safety_stock?: number;
          reorder_point?: number;
          reorder_quantity?: number;
          last_restock_date?: string | null;
          next_restock_date?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      inventory_transactions: {
        Row: {
          id: string;
          product_id: string;
          warehouse_location: string;
          quantity_change: number;
          type: string;
          reference_id: string | null;
          reference_type: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          warehouse_location: string;
          quantity_change: number;
          type: string;
          reference_id?: string | null;
          reference_type?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          product_id?: string;
          warehouse_location?: string;
          quantity_change?: number;
          type?: string;
          reference_id?: string | null;
          reference_type?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      gift_cards: {
        Row: {
          id: string;
          code: string;
          initial_balance: number;
          current_balance: number;
          purchased_by: string | null;
          recipient_email: string | null;
          recipient_name: string | null;
          message: string | null;
          is_active: boolean;
          expires_at: string | null;
          redeemed_by: string | null;
          redeemed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          initial_balance: number;
          current_balance: number;
          purchased_by?: string | null;
          recipient_email?: string | null;
          recipient_name?: string | null;
          message?: string | null;
          is_active?: boolean;
          expires_at?: string | null;
          redeemed_by?: string | null;
          redeemed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          current_balance?: number;
          recipient_email?: string | null;
          recipient_name?: string | null;
          message?: string | null;
          is_active?: boolean;
          expires_at?: string | null;
          redeemed_by?: string | null;
          redeemed_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      gift_card_transactions: {
        Row: {
          id: string;
          gift_card_id: string;
          order_id: string | null;
          amount: number;
          balance_after: number;
          type: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          gift_card_id: string;
          order_id?: string | null;
          amount: number;
          balance_after: number;
          type: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          gift_card_id?: string;
          order_id?: string | null;
          amount?: number;
          balance_after?: number;
          type?: string;
          notes?: string | null;
        };
        Relationships: [];
      };
      omni_interaction_log: {
        Row: {
          id: string;
          user_id: string | null;
          session_id: string | null;
          channel: string;
          direction: string;
          content: string;
          content_type: string;
          sentiment_score: number | null;
          intent: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          session_id?: string | null;
          channel: string;
          direction: string;
          content: string;
          content_type?: string;
          sentiment_score?: number | null;
          intent?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          user_id?: string | null;
          session_id?: string | null;
          channel?: string;
          direction?: string;
          content?: string;
          content_type?: string;
          sentiment_score?: number | null;
          intent?: string | null;
          metadata?: Json | null;
        };
        Relationships: [];
      };
      tickets: {
        Row: {
          id: string;
          ticket_number: string;
          user_id: string | null;
          order_id: string | null;
          subject: string;
          description: string;
          status: string;
          priority: string;
          category: string | null;
          assigned_to: string | null;
          resolved_at: string | null;
          resolution: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          ticket_number: string;
          user_id?: string | null;
          order_id?: string | null;
          subject: string;
          description: string;
          status?: string;
          priority?: string;
          category?: string | null;
          assigned_to?: string | null;
          resolved_at?: string | null;
          resolution?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          ticket_number?: string;
          user_id?: string | null;
          order_id?: string | null;
          subject?: string;
          description?: string;
          status?: string;
          priority?: string;
          category?: string | null;
          assigned_to?: string | null;
          resolved_at?: string | null;
          resolution?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      ticket_comments: {
        Row: {
          id: string;
          ticket_id: string;
          user_id: string | null;
          content: string;
          is_internal: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          user_id?: string | null;
          content: string;
          is_internal?: boolean;
          created_at?: string;
        };
        Update: {
          ticket_id?: string;
          user_id?: string | null;
          content?: string;
          is_internal?: boolean;
        };
        Relationships: [];
      };
      vending_machines: {
        Row: {
          id: string;
          machine_serial: string;
          organization_id: string;
          name: string;
          location: string;
          coordinates: Json | null;
          status: string;
          last_checkin: string | null;
          firmware_version: string | null;
          config: Json | null;
          total_sales: number;
          total_transactions: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          machine_serial: string;
          organization_id: string;
          name: string;
          location: string;
          coordinates?: Json | null;
          status?: string;
          last_checkin?: string | null;
          firmware_version?: string | null;
          config?: Json | null;
          total_sales?: number;
          total_transactions?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          machine_serial?: string;
          name?: string;
          location?: string;
          coordinates?: Json | null;
          status?: string;
          last_checkin?: string | null;
          firmware_version?: string | null;
          config?: Json | null;
          total_sales?: number;
          total_transactions?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      vending_machine_inventory: {
        Row: {
          id: string;
          machine_id: string;
          product_id: string;
          slot_number: number;
          quantity: number;
          max_quantity: number;
          price: number;
          last_restocked: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          machine_id: string;
          product_id: string;
          slot_number: number;
          quantity?: number;
          max_quantity?: number;
          price: number;
          last_restocked?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          slot_number?: number;
          quantity?: number;
          max_quantity?: number;
          price?: number;
          last_restocked?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      vending_transactions: {
        Row: {
          id: string;
          machine_id: string;
          product_id: string;
          slot_number: number;
          quantity: number;
          price: number;
          payment_method: string | null;
          transaction_ref: string | null;
          qr_redemption_code: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          machine_id: string;
          product_id: string;
          slot_number: number;
          quantity?: number;
          price: number;
          payment_method?: string | null;
          transaction_ref?: string | null;
          qr_redemption_code?: string | null;
          created_at?: string;
        };
        Update: {
          machine_id?: string;
          product_id?: string;
          slot_number?: number;
          quantity?: number;
          price?: number;
          payment_method?: string | null;
          transaction_ref?: string | null;
          qr_redemption_code?: string | null;
        };
        Relationships: [];
      };
      qr_redemptions: {
        Row: {
          id: string;
          code: string;
          user_id: string;
          order_id: string | null;
          product_id: string;
          machine_id: string | null;
          status: string;
          expires_at: string;
          redeemed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          user_id: string;
          order_id?: string | null;
          product_id: string;
          machine_id?: string | null;
          status?: string;
          expires_at: string;
          redeemed_at?: string | null;
          created_at?: string;
        };
        Update: {
          code?: string;
          user_id?: string;
          order_id?: string | null;
          product_id?: string;
          machine_id?: string | null;
          status?: string;
          expires_at?: string;
          redeemed_at?: string | null;
        };
        Relationships: [];
      };
      storefronts: {
        Row: {
          id: string;
          name: string;
          slug: string;
          domain: string | null;
          logo_url: string | null;
          theme: Json | null;
          settings: Json | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          domain?: string | null;
          logo_url?: string | null;
          theme?: Json | null;
          settings?: Json | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          domain?: string | null;
          logo_url?: string | null;
          theme?: Json | null;
          settings?: Json | null;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_variants: {
        Row: {
          id: string;
          product_id: string;
          sku: string;
          name: string;
          size: string | null;
          flavor: string | null;
          pack_count: number | null;
          price: number;
          compare_at_price: number | null;
          cost_price: number | null;
          weight_oz: number | null;
          stock_level: number;
          barcode: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          sku: string;
          name: string;
          size?: string | null;
          flavor?: string | null;
          pack_count?: number | null;
          price: number;
          compare_at_price?: number | null;
          cost_price?: number | null;
          weight_oz?: number | null;
          stock_level?: number;
          barcode?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          product_id?: string;
          sku?: string;
          name?: string;
          size?: string | null;
          flavor?: string | null;
          pack_count?: number | null;
          price?: number;
          compare_at_price?: number | null;
          cost_price?: number | null;
          weight_oz?: number | null;
          stock_level?: number;
          barcode?: string | null;
          is_active?: boolean;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_bundles: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          image_url: string | null;
          images: string[];
          bundle_price: number;
          compare_at_price: number | null;
          bundle_type: BundleType;
          custom_pick_count: number | null;
          custom_eligible_product_ids: string[];
          category: string | null;
          tags: string[];
          is_active: boolean;
          is_seasonal: boolean;
          available_from: string | null;
          available_until: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          image_url?: string | null;
          images?: string[];
          bundle_price: number;
          compare_at_price?: number | null;
          bundle_type?: BundleType;
          custom_pick_count?: number | null;
          custom_eligible_product_ids?: string[];
          category?: string | null;
          tags?: string[];
          is_active?: boolean;
          is_seasonal?: boolean;
          available_from?: string | null;
          available_until?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          description?: string | null;
          image_url?: string | null;
          images?: string[];
          bundle_price?: number;
          compare_at_price?: number | null;
          bundle_type?: BundleType;
          custom_pick_count?: number | null;
          custom_eligible_product_ids?: string[];
          category?: string | null;
          tags?: string[];
          is_active?: boolean;
          is_seasonal?: boolean;
          available_from?: string | null;
          available_until?: string | null;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_bundle_items: {
        Row: {
          id: string;
          bundle_id: string;
          product_id: string;
          variant_id: string | null;
          quantity: number;
          sort_order: number;
        };
        Insert: {
          id?: string;
          bundle_id: string;
          product_id: string;
          variant_id?: string | null;
          quantity?: number;
          sort_order?: number;
        };
        Update: {
          bundle_id?: string;
          product_id?: string;
          variant_id?: string | null;
          quantity?: number;
          sort_order?: number;
        };
        Relationships: [];
      };
      product_nutrition: {
        Row: {
          id: string;
          product_id: string;
          variant_id: string | null;
          serving_size: string | null;
          servings_per_container: number | null;
          calories: number | null;
          total_fat_g: number | null;
          saturated_fat_g: number | null;
          trans_fat_g: number | null;
          cholesterol_mg: number | null;
          sodium_mg: number | null;
          total_carbohydrate_g: number | null;
          dietary_fiber_g: number | null;
          total_sugars_g: number | null;
          added_sugars_g: number | null;
          protein_g: number | null;
          vitamin_d_mcg: number | null;
          calcium_mg: number | null;
          iron_mg: number | null;
          potassium_mg: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          variant_id?: string | null;
          serving_size?: string | null;
          servings_per_container?: number | null;
          calories?: number | null;
          total_fat_g?: number | null;
          saturated_fat_g?: number | null;
          trans_fat_g?: number | null;
          cholesterol_mg?: number | null;
          sodium_mg?: number | null;
          total_carbohydrate_g?: number | null;
          dietary_fiber_g?: number | null;
          total_sugars_g?: number | null;
          added_sugars_g?: number | null;
          protein_g?: number | null;
          vitamin_d_mcg?: number | null;
          calcium_mg?: number | null;
          iron_mg?: number | null;
          potassium_mg?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          product_id?: string;
          variant_id?: string | null;
          serving_size?: string | null;
          servings_per_container?: number | null;
          calories?: number | null;
          total_fat_g?: number | null;
          saturated_fat_g?: number | null;
          trans_fat_g?: number | null;
          cholesterol_mg?: number | null;
          sodium_mg?: number | null;
          total_carbohydrate_g?: number | null;
          dietary_fiber_g?: number | null;
          total_sugars_g?: number | null;
          added_sugars_g?: number | null;
          protein_g?: number | null;
          vitamin_d_mcg?: number | null;
          calcium_mg?: number | null;
          iron_mg?: number | null;
          potassium_mg?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_reviews: {
        Row: {
          id: string;
          product_id: string;
          user_id: string;
          order_id: string | null;
          rating: number;
          title: string | null;
          body: string | null;
          taste_rating: number | null;
          value_rating: number | null;
          preparation_ease: number | null;
          images: string[];
          status: ReviewStatus;
          is_verified_purchase: boolean;
          helpful_count: number;
          admin_response: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          user_id: string;
          order_id?: string | null;
          rating: number;
          title?: string | null;
          body?: string | null;
          taste_rating?: number | null;
          value_rating?: number | null;
          preparation_ease?: number | null;
          images?: string[];
          status?: ReviewStatus;
          is_verified_purchase?: boolean;
          helpful_count?: number;
          admin_response?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          product_id?: string;
          user_id?: string;
          order_id?: string | null;
          rating?: number;
          title?: string | null;
          body?: string | null;
          taste_rating?: number | null;
          value_rating?: number | null;
          preparation_ease?: number | null;
          images?: string[];
          status?: ReviewStatus;
          is_verified_purchase?: boolean;
          helpful_count?: number;
          admin_response?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_relationships: {
        Row: {
          id: string;
          source_product_id: string;
          target_product_id: string;
          relationship_type: RelationshipType;
          score: number;
          is_manual: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          source_product_id: string;
          target_product_id: string;
          relationship_type: RelationshipType;
          score?: number;
          is_manual?: boolean;
          created_at?: string;
        };
        Update: {
          source_product_id?: string;
          target_product_id?: string;
          relationship_type?: RelationshipType;
          score?: number;
          is_manual?: boolean;
        };
        Relationships: [];
      };
      price_lists: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          currency: string;
          priority: number;
          applies_to_channels: string[];
          applies_to_roles: UserRole[];
          applies_to_dealer_tiers: DealerTier[];
          effective_from: string | null;
          effective_until: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          currency?: string;
          priority?: number;
          applies_to_channels?: string[];
          applies_to_roles?: UserRole[];
          applies_to_dealer_tiers?: DealerTier[];
          effective_from?: string | null;
          effective_until?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          description?: string | null;
          currency?: string;
          priority?: number;
          applies_to_channels?: string[];
          applies_to_roles?: UserRole[];
          applies_to_dealer_tiers?: DealerTier[];
          effective_from?: string | null;
          effective_until?: string | null;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      price_list_entries: {
        Row: {
          id: string;
          price_list_id: string;
          product_id: string | null;
          category: string | null;
          fixed_price: number | null;
          discount_percentage: number | null;
          quantity_breaks: Json | null;
          min_quantity: number | null;
          max_quantity: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          price_list_id: string;
          product_id?: string | null;
          category?: string | null;
          fixed_price?: number | null;
          discount_percentage?: number | null;
          quantity_breaks?: Json | null;
          min_quantity?: number | null;
          max_quantity?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          price_list_id?: string;
          product_id?: string | null;
          category?: string | null;
          fixed_price?: number | null;
          discount_percentage?: number | null;
          quantity_breaks?: Json | null;
          min_quantity?: number | null;
          max_quantity?: number | null;
          is_active?: boolean;
        };
        Relationships: [];
      };
      promotions: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          internal_notes: string | null;
          discount_type: DiscountType;
          trigger_type: TriggerType;
          coupon_code: string | null;
          discount_value: number;
          max_discount_amount: number | null;
          bogo_buy_quantity: number | null;
          bogo_get_quantity: number | null;
          bogo_get_discount_pct: number | null;
          volume_breaks: Json | null;
          spend_breaks: Json | null;
          min_order_amount: number | null;
          min_quantity: number | null;
          applicable_product_ids: string[];
          applicable_categories: string[];
          excluded_product_ids: string[];
          first_order_only: boolean;
          subscription_only: boolean;
          stacking_group: string | null;
          priority: number;
          is_stackable: boolean;
          usage_limit: number | null;
          usage_count: number;
          per_user_limit: number | null;
          starts_at: string | null;
          ends_at: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          internal_notes?: string | null;
          discount_type: DiscountType;
          trigger_type?: TriggerType;
          coupon_code?: string | null;
          discount_value?: number;
          max_discount_amount?: number | null;
          bogo_buy_quantity?: number | null;
          bogo_get_quantity?: number | null;
          bogo_get_discount_pct?: number | null;
          volume_breaks?: Json | null;
          spend_breaks?: Json | null;
          min_order_amount?: number | null;
          min_quantity?: number | null;
          applicable_product_ids?: string[];
          applicable_categories?: string[];
          excluded_product_ids?: string[];
          first_order_only?: boolean;
          subscription_only?: boolean;
          stacking_group?: string | null;
          priority?: number;
          is_stackable?: boolean;
          usage_limit?: number | null;
          usage_count?: number;
          per_user_limit?: number | null;
          starts_at?: string | null;
          ends_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          internal_notes?: string | null;
          discount_type?: DiscountType;
          trigger_type?: TriggerType;
          coupon_code?: string | null;
          discount_value?: number;
          max_discount_amount?: number | null;
          bogo_buy_quantity?: number | null;
          bogo_get_quantity?: number | null;
          bogo_get_discount_pct?: number | null;
          volume_breaks?: Json | null;
          spend_breaks?: Json | null;
          min_order_amount?: number | null;
          min_quantity?: number | null;
          applicable_product_ids?: string[];
          applicable_categories?: string[];
          excluded_product_ids?: string[];
          first_order_only?: boolean;
          subscription_only?: boolean;
          stacking_group?: string | null;
          priority?: number;
          is_stackable?: boolean;
          usage_limit?: number | null;
          usage_count?: number;
          per_user_limit?: number | null;
          starts_at?: string | null;
          ends_at?: string | null;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      promotion_redemptions: {
        Row: {
          id: string;
          promotion_id: string;
          user_id: string;
          order_id: string | null;
          discount_amount: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          promotion_id: string;
          user_id: string;
          order_id?: string | null;
          discount_amount: number;
          created_at?: string;
        };
        Update: {
          promotion_id?: string;
          user_id?: string;
          order_id?: string | null;
          discount_amount?: number;
        };
        Relationships: [];
      };
      credit_ledger: {
        Row: {
          id: string;
          user_id: string;
          amount: number;
          type: CreditType;
          reference_id: string | null;
          reference_type: string | null;
          description: string | null;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          amount: number;
          type: CreditType;
          reference_id?: string | null;
          reference_type?: string | null;
          description?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          amount?: number;
          type?: CreditType;
          reference_id?: string | null;
          reference_type?: string | null;
          description?: string | null;
          expires_at?: string | null;
        };
        Relationships: [];
      };
      referrals: {
        Row: {
          id: string;
          referrer_id: string;
          referee_id: string | null;
          referral_code: string;
          referee_email: string | null;
          referrer_reward_value: number;
          referee_reward_value: number;
          status: ReferralStatus;
          converted_order_id: string | null;
          rewarded_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          referrer_id: string;
          referee_id?: string | null;
          referral_code: string;
          referee_email?: string | null;
          referrer_reward_value?: number;
          referee_reward_value?: number;
          status?: ReferralStatus;
          converted_order_id?: string | null;
          rewarded_at?: string | null;
          created_at?: string;
        };
        Update: {
          referrer_id?: string;
          referee_id?: string | null;
          referral_code?: string;
          referee_email?: string | null;
          referrer_reward_value?: number;
          referee_reward_value?: number;
          status?: ReferralStatus;
          converted_order_id?: string | null;
          rewarded_at?: string | null;
        };
        Relationships: [];
      };
      gift_orders: {
        Row: {
          id: string;
          order_id: string;
          sender_id: string;
          recipient_name: string;
          recipient_email: string;
          gift_message: string | null;
          delivery_date: string | null;
          gift_type: GiftType;
          num_deliveries: number;
          notified_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          sender_id: string;
          recipient_name: string;
          recipient_email: string;
          gift_message?: string | null;
          delivery_date?: string | null;
          gift_type?: GiftType;
          num_deliveries?: number;
          notified_at?: string | null;
          created_at?: string;
        };
        Update: {
          order_id?: string;
          sender_id?: string;
          recipient_name?: string;
          recipient_email?: string;
          gift_message?: string | null;
          delivery_date?: string | null;
          gift_type?: GiftType;
          num_deliveries?: number;
          notified_at?: string | null;
        };
        Relationships: [];
      };
      b2b_contracts: {
        Row: {
          id: string;
          organization_id: string;
          price_list_id: string;
          contract_number: string;
          name: string;
          annual_volume_commitment: number | null;
          annual_spend_commitment: number | null;
          effective_from: string;
          effective_until: string;
          auto_renew: boolean;
          status: ContractStatus;
          signed_at: string | null;
          notes: string | null;
          document_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          price_list_id: string;
          contract_number: string;
          name: string;
          annual_volume_commitment?: number | null;
          annual_spend_commitment?: number | null;
          effective_from: string;
          effective_until: string;
          auto_renew?: boolean;
          status?: ContractStatus;
          signed_at?: string | null;
          notes?: string | null;
          document_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          organization_id?: string;
          price_list_id?: string;
          contract_number?: string;
          name?: string;
          annual_volume_commitment?: number | null;
          annual_spend_commitment?: number | null;
          effective_from?: string;
          effective_until?: string;
          auto_renew?: boolean;
          status?: ContractStatus;
          signed_at?: string | null;
          notes?: string | null;
          document_url?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      promo_codes: {
        Row: {
          id: string;
          code: string;
          description: string | null;
          discount_type: string;
          discount_value: number;
          min_order_amount: number | null;
          max_discount: number | null;
          usage_limit: number | null;
          usage_count: number;
          per_user_limit: number | null;
          valid_from: string;
          valid_until: string | null;
          applicable_products: string[] | null;
          applicable_categories: string[] | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          description?: string | null;
          discount_type: string;
          discount_value: number;
          min_order_amount?: number | null;
          max_discount?: number | null;
          usage_limit?: number | null;
          usage_count?: number;
          per_user_limit?: number | null;
          valid_from?: string;
          valid_until?: string | null;
          applicable_products?: string[] | null;
          applicable_categories?: string[] | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          code?: string;
          description?: string | null;
          discount_type?: string;
          discount_value?: number;
          min_order_amount?: number | null;
          max_discount?: number | null;
          usage_limit?: number | null;
          usage_count?: number;
          per_user_limit?: number | null;
          valid_from?: string;
          valid_until?: string | null;
          applicable_products?: string[] | null;
          applicable_categories?: string[] | null;
          is_active?: boolean;
        };
        Relationships: [];
      };
      product_recipes: {
        Row: {
          id: string;
          product_id: string;
          title: string;
          description: string | null;
          chef_name: string;
          chef_title: string | null;
          chef_image_url: string | null;
          difficulty: "easy" | "medium" | "advanced";
          prep_time_minutes: number | null;
          cook_time_minutes: number | null;
          servings: number;
          ingredients: Json;
          steps: Json;
          tips: string[] | null;
          tags: string[];
          video_url: string | null;
          image_url: string | null;
          is_featured: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          title: string;
          description?: string | null;
          chef_name: string;
          chef_title?: string | null;
          chef_image_url?: string | null;
          difficulty?: "easy" | "medium" | "advanced";
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          servings?: number;
          ingredients: Json;
          steps: Json;
          tips?: string[] | null;
          tags?: string[];
          video_url?: string | null;
          image_url?: string | null;
          is_featured?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          product_id?: string;
          title?: string;
          description?: string | null;
          chef_name?: string;
          chef_title?: string | null;
          chef_image_url?: string | null;
          difficulty?: "easy" | "medium" | "advanced";
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          servings?: number;
          ingredients?: Json;
          steps?: Json;
          tips?: string[] | null;
          tags?: string[];
          video_url?: string | null;
          image_url?: string | null;
          is_featured?: boolean;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      wishlists: {
        Row: {
          id: string;
          user_id: string;
          product_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          product_id: string;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          product_id?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: UserRole;
      order_status: OrderStatus;
      subscription_status: SubscriptionStatus;
      box_size: BoxSize;
      dealer_tier: DealerTier;
      interaction_channel: InteractionChannel;
      machine_status: MachineStatus;
      bundle_type: BundleType;
      review_status: ReviewStatus;
      relationship_type: RelationshipType;
      discount_type: DiscountType;
      trigger_type: TriggerType;
      credit_type: CreditType;
      referral_status: ReferralStatus;
      gift_type: GiftType;
      contract_status: ContractStatus;
    };
  };
}

// Helper types for easier access
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Organization = Database["public"]["Tables"]["organizations"]["Row"];
export type Product = Database["public"]["Tables"]["aura_products"]["Row"];
export type Category = Database["public"]["Tables"]["categories"]["Row"];
export type Subscription = Database["public"]["Tables"]["aura_subscriptions"]["Row"];
export type SubscriptionSelection = Database["public"]["Tables"]["subscription_selections"]["Row"];
export type Order = Database["public"]["Tables"]["aura_orders"]["Row"];
export type OrderItemRow = Database["public"]["Tables"]["order_items"]["Row"];
export type Dealer = Database["public"]["Tables"]["dealers"]["Row"];
export type CommissionTransaction = Database["public"]["Tables"]["commission_transactions"]["Row"];
export type Inventory = Database["public"]["Tables"]["inventory"]["Row"];
export type InventoryTransaction = Database["public"]["Tables"]["inventory_transactions"]["Row"];
export type GiftCard = Database["public"]["Tables"]["gift_cards"]["Row"];
export type GiftCardTransaction = Database["public"]["Tables"]["gift_card_transactions"]["Row"];
export type InteractionLog = Database["public"]["Tables"]["omni_interaction_log"]["Row"];
export type Ticket = Database["public"]["Tables"]["tickets"]["Row"];
export type TicketComment = Database["public"]["Tables"]["ticket_comments"]["Row"];
export type VendingMachine = Database["public"]["Tables"]["vending_machines"]["Row"];
export type VendingMachineInventory = Database["public"]["Tables"]["vending_machine_inventory"]["Row"];
export type VendingTransaction = Database["public"]["Tables"]["vending_transactions"]["Row"];
export type QrRedemption = Database["public"]["Tables"]["qr_redemptions"]["Row"];
export type Storefront = Database["public"]["Tables"]["storefronts"]["Row"];
export type PromoCode = Database["public"]["Tables"]["promo_codes"]["Row"];
export type OrganizationPriceRule = Database["public"]["Tables"]["organization_price_rules"]["Row"];
export type ProductVariant = Database["public"]["Tables"]["product_variants"]["Row"];
export type ProductBundle = Database["public"]["Tables"]["product_bundles"]["Row"];
export type ProductBundleItem = Database["public"]["Tables"]["product_bundle_items"]["Row"];
export type ProductNutrition = Database["public"]["Tables"]["product_nutrition"]["Row"];
export type ProductReview = Database["public"]["Tables"]["product_reviews"]["Row"];
export type ProductRelationship = Database["public"]["Tables"]["product_relationships"]["Row"];
export type PriceList = Database["public"]["Tables"]["price_lists"]["Row"];
export type PriceListEntry = Database["public"]["Tables"]["price_list_entries"]["Row"];
export type Promotion = Database["public"]["Tables"]["promotions"]["Row"];
export type PromotionRedemption = Database["public"]["Tables"]["promotion_redemptions"]["Row"];
export type CreditLedgerEntry = Database["public"]["Tables"]["credit_ledger"]["Row"];
export type Referral = Database["public"]["Tables"]["referrals"]["Row"];
export type GiftOrder = Database["public"]["Tables"]["gift_orders"]["Row"];
export type B2BContract = Database["public"]["Tables"]["b2b_contracts"]["Row"];
export type Wishlist = Database["public"]["Tables"]["wishlists"]["Row"];
export type ProductRecipe = Database["public"]["Tables"]["product_recipes"]["Row"];
